### ISSUE TITLE
SavageFactions compatibility

### ISSUE THREAD

**Issue by SlimeDog** [mcmonkeyprojects/Sentinel#264]
Spigot 1.13.1 latest
Citizens 2.0.24-b1570
Sentinel 1.6.2-b190
SavageFactions 1.6.9.5-U0.2.1-RC-1.4-RC-2

On start-up:
```
[06:58:56] [Server thread/INFO]: [Sentinel] Enabling Sentinel v1.6.2 (build 190)
[06:58:56] [Server thread/INFO]: [Sentinel] Sentinel loading...
[06:58:56] [Server thread/INFO]: [Sentinel] Sentinel loaded!
[06:58:56] [Server thread/INFO]: [Sentinel] Vault linked! Group targets will work.
[06:58:56] [Server thread/WARN]: java.lang.NoClassDefFoundError: com/massivecraft/factions/RelationParticipator
[06:58:56] [Server thread/WARN]:        at org.mcmonkey.sentinel.SentinelPlugin.onEnable(SentinelPlugin.java:208)
[06:58:56] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[06:58:56] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339)
[06:58:56] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[06:58:56] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:428)
[06:58:56] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:342)
[06:58:56] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:584)
[06:58:56] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:546)
[06:58:56] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:424)
[06:58:56] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294)
[06:58:56] [Server thread/WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702)
[06:58:56] [Server thread/WARN]:        at java.lang.Thread.run(Thread.java:748)
[06:58:56] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: com.massivecraft.factions.RelationParticipator
[06:58:56] [Server thread/WARN]:        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[06:58:56] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154)
[06:58:56] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100)
[06:58:56] [Server thread/WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[06:58:56] [Server thread/WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[06:58:56] [Server thread/WARN]:        ... 12 more
```

**Comment by mcmonkey4eva** [comment]
This is not a Sentinel issue.
You're running a plugin that identifies itself in `plugin.yml` as being Factions, but is not Factions.

An error from loading trouble is inevitable with that setup.

The error shouldn't cause any trouble with Sentinel functioning per normal.
