### ISSUE TITLE
Error trying to make a sentinal

### ISSUE THREAD

**Issue by Lightning11wins** [mcmonkeyprojects/Sentinel#280]
The output of command `/version` on my server is: git-spigot-b3c0272-7723b90 (MC: 1.8.7) (Implementing API Version 1.8.7-R0.1-SNAPSHOT)
The output of command `/version citizens` on my server is: 2.0.16-SNAPSHOT (build 1267)
The output of command `/version sentinel` on my server is: 1.0 (build 90)
My full `Sentinel/config.yml` file is:

```
# Sentinel plugin configuration file

# Default settings for a new NPC
sentinel defaults:
    # Whether 'close quarters' NPCs should chase targets.
    close chase target: true
    # Whether 'ranged attack' NPCs should chase targets.
    ranged chase target: false
    # How much damage to do. -1 for calculated values.
    damage: -1
    # How much armor to have (percentage). -1 for calculated values.
    armor: -1
    # How much health to have.
    health: 20
    # Whether this NPC is invincible.
    invincible: false
    # Attack rate, in ticks.
    attack rate: 25
    # Heal rate, in ticks.
    heal rate: 40
    # Whether this NPC fights back.
    fightback: true
    # Whether this NPC needs ammo to fight with.
    needs ammo: false
    # Whether this NPC will avoid damaging non-targets.
    safe shot: true
    # Default respawn time, in ticks.
    respawn time: 120
    # Whether enemy mobs killed by this NPC should drop items.
    enemy drops: true
    # How long to target temporary enemies for, in ticks. 0 means never-forget.
    enemy target time: 0
    # What movement (chase) speed should be used, as a multiple of the default speed.
    speed: 1.2
    # Whether to automatically switch to the most appropriate available weapon. (Bow at range, or sword up close).
    autoswitch: true
    # Accuracy offset, 0 means perfectly accurate, 5 means pretty inaccurate.
    accuracy: 0.5

random:
    # What sound to play when the "spectral" attack is used.
    spectral sound: ENTITY_VILLAGER_YES
    # Whether to use 'workaround' mode of fist damage.
    workaround damage: false
    # Whether to enforce drops even when 'keepInventory' or similar are enabled.
    workaround drops: false
    # Whether to permit death messages to show for Sentinel NPC deaths.
    death messages: true
    # How fast to try to shoot things (EG arrows).
    shoot speed minimum: 30
    # Whether to force damage through (particularly for ranged attacks).
    enforce damage: false
    # Whether NPCs are protected from damage by ignore targets.
    protected: false
    # Whether skull attack is allowed.
    skull allowed: true

# How fast to recalculate, in ticks.
update rate: 10

# Do not touch! (Unless you know what you're doing!)
config version: 7

```

I just got this plugin and was trying to make an NPC player I had just created. I ran the command "/trait add Sentinel" and got an error. I am running a few plugins besides Cit.s and sentinel, they are _Vault_, _MageCraft_ (a plugin I am developing with for a _completely_ different purpose!), and _Bacteria-Bash_ (also unrelated, and being developed for a different purpose)

**Error Message:**
Please report this error: [See console]
java.lang.NoDefFoundError: Could not initialize class
org.mcmonky.sentinel.SentinelTarget

**Console Message:**
```
java.lang.NoClassDefFoundError: Could not initialize class org.mcmonkey.sentinel.SentinelTarget
[15:29:03 WARN]: 	at org.mcmonkey.sentinel.SentinelTrait.onAttach(SentinelTrait.java:414)
[15:29:03 WARN]: 	at net.citizensnpcs.api.trait.Trait.linkToNPC(Trait.java:46)
[15:29:03 WARN]: 	at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:99)
[15:29:03 WARN]: 	at net.citizensnpcs.api.npc.AbstractNPC.addTrait(AbstractNPC.java:88)
[15:29:03 WARN]: 	at net.citizensnpcs.commands.TraitCommands.addTrait(TraitCommands.java:64)
[15:29:03 WARN]: 	at net.citizensnpcs.commands.TraitCommands.add(TraitCommands.java:54)
[15:29:03 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:29:03 WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:29:03 WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:29:03 WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[15:29:03 WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:152)
[15:29:03 WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
[15:29:03 WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:175)
[15:29:03 WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:238)
[15:29:03 WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[15:29:03 WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[15:29:03 WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:642)
[15:29:03 WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1135)
[15:29:03 WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:970)
[15:29:03 WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[15:29:03 WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[15:29:03 WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[15:29:03 WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[15:29:03 WARN]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[15:29:03 WARN]: 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SystemUtils.java:19)
[15:29:03 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:718)
[15:29:03 WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:367)
[15:29:03 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:657)
[15:29:03 WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:560)
[15:29:03 WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Lightning11wins** [comment]
I hope this isn't too bad

**Comment by mergu** [comment]
You'll need to update everything. 1.8.7 is 5 years old (and it's not even the latest 1.8 patch) and your sentinel and citizens versions are extremely out of date.

Update to:
1.12.2 / 1.13.2: https://www.spigotmc.org/wiki/buildtools/ OR https://papermc.io/ci/
Latest Citizens: http://ci.citizensnpcs.co/job/Citizens2/lastSuccessfulBuild/
Latest Sentinel: https://ci.citizensnpcs.co/job/Sentinel/lastSuccessfulBuild/

**Comment by mcmonkey4eva** [comment]
^ All of that. Running 1.8.7 is ridiculous. Running actual 1.8.8 latest is already bad enough - see https://wiki.citizensnpcs.co/Minecraft_1.8 - ... running an _older version_ of 1.8 is just outright stupid.
The Citizens/Sentinel versions are so far outdated that they don't even make sense to post issues about, as the code we're working with on both projects looks _nothing_ like what those versions contain anymore.

Also: that's not a full original error message, that's a secondary exception. It amounts to "The thing that's broken is still broken". You'd have to find the original error message that says what broke and why to have any hope of diagnosing it.
