### ISSUE TITLE
InvocationTargetException on start-up

### ISSUE THREAD

**Issue by SlimeDog** [mcmonkeyprojects/Sentinel#301]
The output of command `/version` on my server is: 
```
>version
[06:12:06] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-9de398a-8b09d98 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
[06:12:06] [Server thread/INFO]: You are running the latest version
```
The output of command `/version citizens` on my server is: 
```
>version citizens
[06:12:43] [Server thread/INFO]: Citizens version 2.0.25-SNAPSHOT (build 1731)
[06:12:43] [Server thread/INFO]: Website: http://www.citizensnpcs.co
[06:12:43] [Server thread/INFO]: Author: fullwall
[06:12:43] [Server thread/INFO]: CitizensCMD version 2.3.2
[06:12:43] [Server thread/INFO]: Author: Mateus Moreira
```
The output of command `/version sentinel` on my server is: 
```
>version sentinel
[06:13:12] [Server thread/INFO]: Sentinel version 1.9.2 (build 265)
[06:13:12] [Server thread/INFO]: Author: mcmonkey
```
Sentinel/config.yml file (comments elided) is: 
```
sentinel defaults:
    close chase target: true
    ranged chase target: false
    damage: -1
    armor: -1
    health: 20
    invincible: false
    attack rate: 30
    heal rate: 100
    fightback: true
    needs ammo: false
    safe shot: true
    respawn time: 100
    enemy drops: false
    enemy target time: 0
    speed: 1.5
    autoswitch: false
    accuracy: 0
    realistic: false
    reach: 3
    avoid range: 10
    runaway: false
random:
    run away time: 1200
    spectral sound: ENTITY_VILLAGER_YES
    workaround damage: false
    workaround drops: false
    workaround bukkit events: false
    workaround entity chase pathfinder: false
    death messages: true
    shoot speed minimum: 20
    enforce damage: false
    protected: false
    skull allowed: true
    clever ticks: 10
    max health: 2000
    ignore invisible targets: true
    no guard damage: true
    guard follow distance:
        selection range: 4
        minimum: 7
update rate: 10

```

On server start-up:
```
[05:44:53] [Server thread/WARN]: java.lang.reflect.InvocationTargetException
[05:44:53] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[05:44:53] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[05:44:53] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[05:44:53] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[05:44:53] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.entity.MobEntityController.createEntityFromClass(MobEntityController.java:47)
[05:44:53] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.entity.MobEntityController.createEntity(MobEntityController.java:32)
[05:44:53] [Server thread/WARN]: 	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41)
[05:44:53] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:232)
[05:44:53] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:208)
[05:44:53] [Server thread/WARN]: 	at org.mcmonkey.sentinel.SentinelPlugin$1.run(SentinelPlugin.java:267)
[05:44:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81)
[05:44:53] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394)
[05:44:53] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1023)
[05:44:53] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396)
[05:44:53] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:971)
[05:44:53] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:816)
[05:44:53] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[05:44:53] [Server thread/WARN]: Caused by: java.lang.NullPointerException
[05:44:53] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.Entity.<init>(Entity.java:199)
[05:44:53] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityLiving.<init>(EntityLiving.java:144)
[05:44:53] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityInsentient.<init>(EntityInsentient.java:56)
[05:44:53] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityCreature.<init>(EntityCreature.java:10)
[05:44:53] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityAgeable.<init>(EntityAgeable.java:14)
[05:44:53] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityAnimal.<init>(EntityAnimal.java:14)
[05:44:53] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityTameableAnimal.<init>(SourceFile:32)
[05:44:53] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.EntityWolf.<init>(EntityWolf.java:30)
[05:44:53] [Server thread/WARN]: 	at net.citizensnpcs.nms.v1_14_R1.entity.WolfController$EntityWolfNPC.<init>(WolfController.java:50)
[05:44:53] [Server thread/WARN]: 	... 17 more
[05:44:53] [Server thread/WARN]: [Sentinel] Task #72 for Sentinel v1.9.2 (build 265) generated an exception
```

**Comment by mcmonkey4eva** [comment]
You're running the 1.14.3 version of Citizens on a 1.14.4 server.
The needed update was released minutes before you posted this, please update to 1733+: https://ci.citizensnpcs.co/job/Citizens2/

**Comment by SlimeDog** [comment]
Confirmed fixed by Citizens b1733. Thanks.
