### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by silverfox0000** [mcmonkeyprojects/Sentinel#364]
The output of command `/version` on my server is: git-Spigot-dcd1643-e60fc34 (MC: 1.12.2)
The output of command `/version citizens` on my server is: 2.0.24-SNAPSHOT
The output of command `/version sentinel` on my server is: 2.2.6-SNAPSHOT
A pastebin.com link to my  `Sentinel/config.yml` file is: https://pastebin.com/RjWSx2bu

```
[20:47:12 INFO]: SilverFox issued server command: /sentinel
[20:47:12 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'sentinel' in plugin Sentinel v2.2.6-SNAPSHOT (build 408)
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[server.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1399) [server.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1234) [server.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-dcd1643-e60fc34]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_282]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_282]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-dcd1643-e60fc34]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-dcd1643-e60fc34]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_282]
Caused by: java.lang.NoSuchMethodError: net/citizensnpcs/api/npc/NPC.getTraitNullable(Ljava/lang/Class;)Lnet/citizensnpcs/api/trait/Trait; (loaded from file:/home/container/plugins/Citizens.jar by org.bukkit.plugin.java.PluginClassLoader@720646c3) called from class org.mcmonkey.sentinel.commands.SentinelCommand (loaded from file:/home/container/plugins/Sentinel-2.2.6-SNAPSHOT-b408.jar by org.bukkit.plugin.java.PluginClassLoader@1d4f608e).
        at org.mcmonkey.sentinel.commands.SentinelCommand.onCommand(SentinelCommand.java:123) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-dcd1643-e60fc34]
        ... 15 more
```

**Comment by mcmonkey4eva** [comment]
You need to update Citizens, that version is extremely far outdated
