### ISSUE TITLE
/sentinel drops returns error after setting drops for the first time

### ISSUE THREAD

**Issue by SlyyJacob** [mcmonkeyprojects/Sentinel#368]
The output of command /version on my server is: (PLEASE FILL IN)
Paper git-Paper-88 (1.17.1)
The output of command /version citizens on my server is: (PLEASE FILL IN)
2.0.28 - snapshot (2346)
The output of command /version sentinel on my server is: (PLEASE FILL IN)
2.3.0 - snapshot (417)
A pastebin.com link to my (full!) Sentinel/config.yml file is: (PLEASE FILL IN)
https://pastebin.com/naJKSrPL

https://pastebin.com/TyKh0FdX

After setting /sentinel drops for the selected NPC, trying to access the /sentinel drops gui drops editor again returns the following:

![2021-07-09 10_36_02](https://user-images.githubusercontent.com/36818957/125049661-7f001380-e0a1-11eb-8c44-007649adf5c3.jpg)

```
[10:35:37 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.clone()" because "items[i]" is null
[10:35:37 WARN]:        at org.mcmonkey.sentinel.commands.SentinelHealthCommands.drops(SentinelHealthCommands.java:209)
[10:35:37 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:35:37 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[10:35:37 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[10:35:37 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[10:35:37 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
[10:35:37 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
[10:35:37 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
[10:35:37 WARN]:        at org.mcmonkey.sentinel.commands.SentinelCommand.onCommand(SentinelCommand.java:147)
[10:35:37 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[10:35:37 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[10:35:37 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821)
[10:35:37 WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2165)
[10:35:37 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1976)
[10:35:37 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1957)
[10:35:37 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[10:35:37 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[10:35:37 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:36)
[10:35:37 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[10:35:37 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[10:35:37 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23)
[10:35:37 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1348)
[10:35:37 WARN]:        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:190)
[10:35:37 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[10:35:37 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1327)
[10:35:37 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1320)
[10:35:37 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[10:35:37 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1397)
[10:35:37 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1188)
[10:35:37 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[10:35:37 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```

Haven't had issues with this in previous versions. The drops themselves seem to work fine, but you can't access the gui editor again.

**Comment by mcmonkey4eva** [comment]
Oops! Fixed for build 418+ from https://ci.citizensnpcs.co/job/Sentinel/
