### ISSUE TITLE
World Gaurd

### ISSUE THREAD

**Issue by HyperSkys** [mcmonkeyprojects/Sentinel#369]
[01:09:00 INFO]: HyperSkys issued server command: /sentinel wgregion warzone
[01:09:00 WARN]: java.lang.NoClassDefFoundError: com/sk89q/worldguard/WorldGuard
[01:09:00 WARN]:        at org.mcmonkey.sentinel.utilities.SentinelWorldGuardHelper.getRegionFor(SentinelWorldGuardHelper.java:22)
[01:09:00 WARN]:        at org.mcmonkey.sentinel.commands.SentinelChaseCommands.wgRegion(SentinelChaseCommands.java:72)
[01:09:00 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:09:00 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[01:09:00 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:09:00 WARN]:        at java.lang.reflect.Method.invoke(Method.java:498)
[01:09:00 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
[01:09:00 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
[01:09:00 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
[01:09:00 WARN]:        at org.mcmonkey.sentinel.commands.SentinelCommand.onCommand(SentinelCommand.java:145)
[01:09:00 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[01:09:00 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:143)
[01:09:00 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:659)
[01:09:00 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1194)
[01:09:00 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1006)
[01:09:00 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[01:09:00 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[01:09:00 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[01:09:00 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[01:09:00 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[01:09:00 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[01:09:00 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:808)
[01:09:00 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[01:09:00 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:747)
[01:09:00 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:645)
[01:09:00 WARN]:        at java.lang.Thread.run(Thread.java:748)

Blocking NPC From attacking outside region in world guard not working and sending this!

**Comment by mcmonkey4eva** [comment]
Looks like you literally just don't have a modern version of WorldGuard installed.

Relatedly, https://wiki.citizensnpcs.co/Minecraft_1.8
