### ISSUE TITLE
Issue: Sentinel Drops

### ISSUE THREAD

**Issue by TheCoder11** [mcmonkeyprojects/Sentinel#370]
The output of command `/version` on my server is: 3180-Spigot-38e6c03-ca0fe5b (MC: 1.17.1)
The output of command `/version citizens` on my server is: 2.0.28-SNAPSHOT
The output of command `/version sentinel` on my server is: 2.3.0-SNAPSHOT
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: https://pastebin.com/X4WuVS34

When we use /sentinel drops, set drops, then set the drop chances with /sentinel dropchance <id> <chance>, when we use the command /sentinel drops again, it pops up with this error:

java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.ItemStack.clone()" because "items[i]" is null
[19:59:07] [Server thread/WARN]:        at org.mcmonkey.sentinel.commands.SentinelHealthCommands.drops(SentinelHealthCommands.java:209)
[19:59:07] [Server thread/WARN]:        at jdk.internal.reflect.GeneratedMethodAccessor1049.invoke(Unknown Source)
[19:59:07] [Server thread/WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[19:59:07] [Server thread/WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[19:59:07] [Server thread/WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:159)
[19:59:07] [Server thread/WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:91)
[19:59:07] [Server thread/WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:187)
[19:59:07] [Server thread/WARN]:        at org.mcmonkey.sentinel.commands.SentinelCommand.onCommand(SentinelCommand.java:147)
[19:59:07] [Server thread/WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[19:59:07] [Server thread/WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149)
[19:59:07] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:760)
[19:59:07] [Server thread/WARN]:        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:1931)
[19:59:07] [Server thread/WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1770)
[19:59:07] [Server thread/WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1751)
[19:59:07] [Server thread/WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[19:59:07] [Server thread/WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:1)
[19:59:07] [Server thread/WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:30)
[19:59:07] [Server thread/WARN]:        at net.minecraft.server.TickTask.run(SourceFile:18)
[19:59:07] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(SourceFile:151)
[19:59:07] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[19:59:07] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(SourceFile:125)
[19:59:07] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1133)
[19:59:07] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1126)
[19:59:07] [Server thread/WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(SourceFile:134)
[19:59:07] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.sleepForTick(MinecraftServer.java:1110)
[19:59:07] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1039)
[19:59:07] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303)
[19:59:07] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

The NPC still drops their items correctly, but we cannot add or remove any items from the drops.

**Comment by mcmonkey4eva** [comment]
- Those are not valid Citizens or Sentinel versions
- That error was already fixed. This is why we ask for versions - if you used your actual version number, it would be obvious it is not the current version number and therefore probably an already-resolved bug

Update: https://ci.citizensnpcs.co/job/Sentinel/
