### ISSUE TITLE
Illegal plugin.yml content

### ISSUE THREAD

**Issue by SlimeDog** [mcmonkeyprojects/Sentinel#373]
```
>version
[20:55:14] [Server thread/INFO]: This server is running CraftBukkit version 3273-Spigot-3892929-376edf4 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)
[20:55:14] [Server thread/INFO]: You are running the latest version
>version Citizens
[20:55:37] [Server thread/INFO]: Citizens version 2.0.28-SNAPSHOT (build 2395)
[20:55:37] [Server thread/INFO]: Website: http://www.citizensnpcs.co
[20:55:37] [Server thread/INFO]: Author: fullwall
```
The output of command `/version sentinel` on my server is: **(PLEASE FILL IN)**
Sentinel-2.3.5-SNAPSHOT-b438.jar does not load, due to parsing error in plugin.yml -- extra spaces in new addition lines for `deathxp`.

```
[19:18:14] [Server thread/ERROR]: Could not load 'plugins/Sentinel-2.3.5-b438.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:180) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:144) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:409) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:233) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1010) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block mapping
 in 'reader', line 22, column 7:
          sentinel.basic: true
          ^
expected <block end>, but found '<block mapping start>'
 in 'reader', line 72, column 9:
            sentinel.deathxp: true
            ^

        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:617) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:221) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:191) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:146) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:429) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at org.bukkit.plugin.PluginDescriptionFile.<init>(PluginDescriptionFile.java:259) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:175) ~[spigot-1.17.1-3273.jar:3273-Spigot-3892929-376edf4]
        ... 6 more
```

**Comment by mcmonkey4eva** [comment]
Woops, thanks, fixed.

Automatic formatting from IDEs is helpful except when it's the opposite of helpful.
