### ISSUE TITLE
NoSuchMethodError: net.citizensnpcs.api.ai.speech.SpeechContext with latest Citizens build

### ISSUE THREAD

**Issue by HowardZHY** [mcmonkeyprojects/Sentinel#394]
The output of command `/version` on my server is: **(BurritoSpigot version git-BurritoSpigot-bec78e2 (MC: 1.8.9) (Implementing API version 1.8.8-R0.2-SNAPSHOT))**
The output of command `/version citizens` on my server is: **(Citizens version 2.0.32-SNAPSHOT (build 3200))**
The output of command `/version sentinel` on my server is: **(Sentinel version 2.8.0-SNAPSHOT (build 511))**
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: **(https://mclo.gs/w0uoQiZ)**

[17:07:22] [Server thread/INFO]: HowardZHY issued server command: /npc spawn
[17:07:23] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to Sentinel v2.8.0-SNAPSHOT (build 511)
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[BurritoSpigot.jar:git-BurritoSpigot-bec78e2]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[BurritoSpigot.jar:git-BurritoSpigot-bec78e2]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[BurritoSpigot.jar:git-BurritoSpigot-bec78e2]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [BurritoSpigot.jar:git-BurritoSpigot-bec78e2]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [BurritoSpigot.jar:git-BurritoSpigot-bec78e2]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:281) [BurritoSpigot.jar:git-BurritoSpigot-bec78e2]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying.a(SourceFile:126) [BurritoSpigot.jar:git-BurritoSpigot-bec78e2]
	at net.minecraft.server.v1_8_R3.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [BurritoSpigot.jar:git-BurritoSpigot-bec78e2]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [BurritoSpigot.jar:git-BurritoSpigot-bec78e2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [BurritoSpigot.jar:git-BurritoSpigot-bec78e2]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:776) [BurritoSpigot.jar:git-BurritoSpigot-bec78e2]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [BurritoSpigot.jar:git-BurritoSpigot-bec78e2]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715) [BurritoSpigot.jar:git-BurritoSpigot-bec78e2]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618) [BurritoSpigot.jar:git-BurritoSpigot-bec78e2]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.NoSuchMethodError: net.citizensnpcs.api.ai.speech.SpeechContext.<init>(Lnet/citizensnpcs/api/npc/NPC;Ljava/lang/String;Lorg/bukkit/entity/LivingEntity;)V
	at org.mcmonkey.sentinel.SentinelTrait.sayTo(SentinelTrait.java:1849) ~[?:?]
	at org.mcmonkey.sentinel.SentinelTrait.onPlayerMovesInRange(SentinelTrait.java:1900) ~[?:?]
	at org.mcmonkey.sentinel.SentinelEventHandler.onPlayerMovesInRange(SentinelEventHandler.java:408) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor127.invoke(Unknown Source) ~[?:?]
Error appears on console.

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Minecraft_1.8
