### ISSUE TITLE
NoSuchMethodError: net.citizensnpcs.api.ai.speech.SpeechContext with latest Citizens build

### ISSUE THREAD

**Issue by HowardZHY** [mcmonkeyprojects/Sentinel#395]
The output of command `/version` on my server is: **(git-Purpur-2053 (MC: 1.20.1))**
The output of command `/version citizens` on my server is: **(Citizens version 2.0.32-SNAPSHOT (build 3200))**
The output of command `/version sentinel` on my server is: **(Sentinel version 2.8.0-SNAPSHOT (build 511))**
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: **(default)**

[14:12:14 ERROR]: Could not pass event PlayerMoveEvent to Sentinel v2.8.0-SNAPSHOT (build 511)
java.lang.NoSuchMethodError: 'void net.citizensnpcs.api.ai.speech.SpeechContext.<init>(net.citizensnpcs.api.npc.NPC, java.lang.String, org.bukkit.entity.LivingEntity)'
        at org.mcmonkey.sentinel.SentinelTrait.sayTo(SentinelTrait.java:1849) ~[Sentinel-2.8.0-SNAPSHOT-b511.jar:?]
        at org.mcmonkey.sentinel.SentinelTrait.onPlayerMovesInRange(SentinelTrait.java:1900) ~[Sentinel-2.8.0-SNAPSHOT-b511.jar:?]
        at org.mcmonkey.sentinel.SentinelEventHandler.onPlayerMovesInRange(SentinelEventHandler.java:408) ~[Sentinel-2.8.0-SNAPSHOT-b511.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor50.execute(Unknown Source) ~[?:?]

https://mclo.gs/GMSzDq3

**Comment by mcmonkey4eva** [comment]
Oh, https://github.com/CitizensDev/CitizensAPI/commit/7e92c0e8363d397878510f79a0027a784c9b700a broke ABI - build 512 (no changes just recompiled) should fix it.
