### ISSUE TITLE
NPE on server start-up

### ISSUE THREAD

**Issue by SlimeDog** [mcmonkeyprojects/Sentinel#401]
The output of command `/version` on my server is: 
```
> version
[21:54:54 INFO]: This server is running Paper version git-Paper-52 (MC: 1.20.6) (Implementing API version 1.20.6-R0.1-SNAPSHOT) (Git: eee55d0)
You are running the latest version
```
The output of command `/version citizens` on my server is: 
```
> version Citizens
[21:55:22 INFO]: Citizens version 2.0.34-SNAPSHOT (build 3415)
[21:55:22 INFO]: Website: https://www.citizensnpcs.co
[21:55:22 INFO]: Author: fullwall
```
The output of command `/version sentinel` on my server is: 
```
> version Sentinel
[21:55:31 INFO]: Sentinel version 2.8.1-SNAPSHOT (build 518)
[21:55:31 INFO]: Author: mcmonkey

```
A pastebin.com link to my (full!) `Sentinel/config.yml` file is:
```
$ grep -v -e ' *#' -e '^ *$' plugins/Sentinel/config.yml 
sentinel defaults:
    close chase target: true
    ranged chase target: false
    damage: -1
    armor: -1
    health: 20
    invincible: false
    attack rate: 30
    heal rate: 100
    protected: true
    protect from range: 0
    fightback: true
    needs ammo: false
    safe shot: true
    respawn time: 100
    enemy drops: false
    enemy target time: 6000
    speed: 1.5
    autoswitch: false
    accuracy: 0
    realistic: false
    reach: 4.5
    projectile range: 100
    avoid range: 10
    runaway: false
    greet range: 10
    greet rate: 100
    reaction slowdown: 0
    allow knockback: true
    death xp: 0
random:
    run away time: 1200
    spectral sound: ENTITY_VILLAGER_YES
    workaround damage: false
    do native attacks: true
    workaround drops: false
    workaround bukkit events: false
    workaround entity chase pathfinder: true
    death messages: false
    shoot speed minimum: 20
    enforce damage: false
    skull allowed: true
    clever ticks: 10
    ignore invisible targets: true
    no guard damage: true
    enhance los traces: true
    guard follow distance:
        selection range: 4
        minimum: 7
    arrow cleanup time: 200
    block sunburn: true
    retain target: false
    prevent explosion block damage: true
    auto correct pathfinder mode: true
    allow armor stand targets: false
update rate: 10
```

```
[21:37:46] [Server thread/INFO]: [Sentinel] Loading server plugin Sentinel v2.8.1-SNAPSHOT (build 518)
[21:38:18] [Server thread/INFO]: [Sentinel] Enabling Sentinel v2.8.1-SNAPSHOT (build 518)
[21:38:18] [Server thread/INFO]: [Sentinel] Sentinel loading...
[21:38:18] [Server thread/INFO]: [Sentinel] Running on java version: 22.0.1
[21:38:18] [Server thread/INFO]: [Sentinel] Vault linked! Group targets will work.
[21:38:18] [Server thread/INFO]: [Sentinel] Sentinel found WorldGuard! Adding support for it!
...
[21:38:18] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.setAccessible(boolean)" because "dataWatcherAngryField" is null
[21:38:18] [Server thread/WARN]:        at Sentinel-2.8.1-b518.jar//org.mcmonkey.sentinel.utilities.SentinelNMSHelper.init(SentinelNMSHelper.java:81)
[21:38:18] [Server thread/WARN]:        at Sentinel-2.8.1-b518.jar//org.mcmonkey.sentinel.SentinelPlugin.onEnable(SentinelPlugin.java:472)
[21:38:18] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[21:38:18] [Server thread/WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
[21:38:18] [Server thread/WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
[21:38:18] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519)
[21:38:18] [Server thread/WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:639)
[21:38:18] [Server thread/WARN]:        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:551)
[21:38:18] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:682)
[21:38:18] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:441)
[21:38:18] [Server thread/WARN]:        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:324)
[21:38:18] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1140)
[21:38:18] [Server thread/WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326)
[21:38:18] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:1570)
[21:38:18] [Server thread/INFO]: [Sentinel] Sentinel loaded!
```

**Comment by mcmonkey4eva** [comment]
yeah, haven't updated to 1.20.6 yet

**Comment by mcmonkey4eva** [comment]
Builds starting at dev-521 support 1.20.6

**Comment by SlimeDog** [comment]
Looks great on Paper 1.20.6-64. Thanks.
