### ISSUE TITLE
[1.8.8] Error occurred while enabling Sentinel

### ISSUE THREAD

**Issue by HowardZHY** [mcmonkeyprojects/Sentinel#405]
The output of command `/version` on my server is: **(PaperSpigot 1.8.8)**
The output of command `/version citizens` on my server is: **(Citizens v2.0.35-SNAPSHOT (build 3478))**
The output of command `/version sentinel` on my server is: **(v2.9.1-SNAPSHOT (build 525))**
A pastebin.com link to my (full!) `Sentinel/config.yml` file is: **(UNRELATED)**

`java.lang.NoClassDefFoundError: org/bukkit/Particle
	at org.mcmonkey.sentinel.utilities.SentinelAPIBreakageFix.<clinit>(SentinelAPIBreakageFix.java:31) ~[?:?]
	at org.mcmonkey.sentinel.targeting.SentinelTarget.<clinit>(SentinelTarget.java:49) ~[?:?]
	at org.mcmonkey.sentinel.utilities.SentinelVersionCompat.<clinit>(SentinelVersionCompat.java:72) ~[?:?]
	at org.mcmonkey.sentinel.SentinelPlugin.onEnable(SentinelPlugin.java:317) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) `
	
org/bukkit/Particle was added in 1.9, it doesn't exist in 1.8.8, please move the Particle type field to another class that won't be loaded

**Comment by mcmonkey4eva** [comment]
https://wiki.citizensnpcs.co/Minecraft_1.8
